### ISSUE TITLE
List alternate versions of tabs on tab page

### ISSUE THREAD

**Issue by zachpmanson** [zachpmanson/penultimate-guitar#10]
Need to make database more complex, split songs into their own table.  This work has been started in `song-schema` branch.

Currently the scraping function gathers (currently unused) fields like version num and rating, and returns 2 objects: 1 for tab table and 1 for song table.  These are upserted into db and then transformed into classic TabDto object and passed to the frontend.

Need to set up TabDto to take more fields, and set up queries that join tab and song to get the full list of alternate versions.

**Comment by pavo-etc** [comment]
Existing deployed db will need to be reset.  Download the list of taburls first, and then run python script later to regenerate all of these.
