### ISSUE TITLE
Autoscrolling doesn't work on some mobile tabs

### ISSUE THREAD

**Issue by zachpmanson** [zachpmanson/penultimate-guitar#39]
https://pg.zachmanson.com/tab/acdc/highway-to-hell-chords-139966

Autoscrolling is broken on Pixel 4a Firefox for this page, presumably because it has horizontal overflow.  Unclear why this has horizontal overflow.

**Comment by pavo-etc** [comment]
Another example
https://pg.zachmanson.com/tab/pacific-avenue/someday-soon-chords-3301781

**Comment by pavo-etc** [comment]
Why is this have horizonal scrolling
https://pg.zachmanson.com/tab/cottonwood-firing-squad/elephant-chords-3689765

**Comment by pavo-etc** [comment]
https://pg.zachmanson.com/tab/beach-bunny/sports-chords-2676075

**Comment by zachpmanson** [comment]
I think it's because of chord tooltips

![Screenshot_20240707-170806.png](https://github.com/zachpmanson/penultimate-guitar/assets/24368336/a5270ba8-6988-4162-8d5a-ca8b3727cd90)

**Comment by zachpmanson** [comment]
related to #31
